{"name": "Получение заказа неавторизованным пользователем", "status": "passed", "start": 1729183649706, "stop": 1729183650813, "uuid": "a61a4dc9-f9df-4b1d-8b7d-53d84c77d45f", "historyId": "c1a0232f51f2152e9dbf3e387acedd88", "testCaseId": "c1a0232f51f2152e9dbf3e387acedd88", "fullName": "tests.test_take_order_user.TestTakeOrderUser#test_take_order_unauthorized_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_take_order_user"}, {"name": "subSuite", "value": "TestTakeOrderUser"}, {"name": "host", "value": "DESKTOP-2V6LHVH"}, {"name": "thread", "value": "5276-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_take_order_user"}]}