{"name": "Логин с неверным логином ", "status": "passed", "start": 1729183646387, "stop": 1729183647693, "uuid": "3d1b9b7c-e428-49fb-b554-f0ee3577e8a5", "historyId": "eccd167207a17fdcd5ef5a87be9adc45", "testCaseId": "eccd167207a17fdcd5ef5a87be9adc45", "fullName": "tests.test_login.TestLogin#test_login_with_incorrect_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-2V6LHVH"}, {"name": "thread", "value": "5276-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}